### ISSUE TITLE
Navbar

### ISSUE THREAD

**Issue by AliReza1083** [itsme-Subid/Blog-2022#2]
I can make a navbar for your website to look amazing.
Can I do it for you?

if yes, Then assign it to me.

**Comment by itsme-Subid** [comment]
yeah sure

**Comment by AliReza1083** [comment]
Will be working on it. 👌

**Comment by itsme-Subid** [comment]
please work on BetterNav branch

**Comment by AliReza1083** [comment]
For me, There is no BetterNav Branch.
NP, I'll make it.

**Comment by AliReza1083** [comment]
I'm really Sorry.

**Comment by itsme-Subid** [comment]
Thanks for trying to make my navbar better
